export const constants = {
  ADD_INITIAL_DATA: 'ADD_INITIAL_DATA',
  ADD_FILTER_DATA: 'ADD_FILTER_DATA',
  ADD_LOADMORE_DATA: 'ADD_LOADMORE_DATA',
  CLEAR_ADD_LOADMORE__DATA: 'CLEAR_ADD_LOADMORE__DATA',
  CLEAR_INITIAL_DATA: 'CLEAR_INITIAL_DATA',
  SET_STORE_CONFIG_DATA: 'SET_STORE_CONFIG_DATA',
  SET_NAVIGATION_DATA: 'SET_NAVIGATION_DATA',
  SET_PRODUCT_DETAILS_DATA: 'SET_PRODUCT_DETAILS_DATA',
  SET_PRODUCT_COLOR: 'SET_PRODUCT_COLOR',
  SET_SELECTED_SIZE: 'SET_SELECTED_SIZE',
  SET_PRODUCT_VARIANT: 'SET_PRODUCT_VARIANT',
  SET_RELATED_PRODUCT: 'SET_RELATED_PRODUCT',
  RESET_PRODUCT_DETAILS: 'RESET_PRODUCT_DETAILS',
  SET_SEARCH_ACTIVE: 'SET_SEARCH_ACTIVE',
  SET_SEARCH_OVERLAY_ACTIVE: 'SET_SEARCH_OVERLAY_ACTIVE',
  SET_TOAST_SHOW: 'SET_TOAST_SHOW',
  SET_TOAST_ERROR: 'SET_TOAST_ERROR',
  SET_TOAST_DATA: 'SET_TOAST_DATA',
  SET_CART_LOADING: 'SET_CART_LOADING',
  SET_PROMOTION_DATA: 'SET_PROMOTION_DATA',

  // Mini cart constants
  // CLEAR_MINI_CART_DATA: 'CLEAR_MINI_CART_DATA',
  UPDATE_PRODUCT_ACTION: 'UPDATE_PRODUCT_ACTION',
  MINI_CART_DATA: 'MINI_CART_DATA',
  MINI_CART_ACTION: 'MINI_CART_ACTION',
  UPDATE_CART_DATA: 'UPDATE_CART_DATA',
  CLEAR_UPDATE_CART_DATA: 'CLEAR_UPDATE_CART_DATA',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',

  EDIT_CART_ITEM: 'EDIT_CART_ITEM',
  EDIT_CART_PRODUCT_COLOR: 'EDIT_CART_PRODUCT_COLOR',
  EDIT_CART_SELECTED_SIZE: 'EDIT_CART_SELECTED_SIZE',
  EDIT_CART_PRODUCT_VARIANT: 'EDIT_CART_PRODUCT_VARIANT',
  RESET_EDIT_CART: 'RESET_EDIT_CART',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',

  //Coupon codes
  GET_ALL_COUPON_CODES: 'GET_ALL_COUPON_CODES',
  APPLY_COUPON_CODE_SUCCESS: 'APPLY_COUPON_CODE_SUCCESS',
  REMOVE_COUPON_CODE_SUCCESS: 'REMOVE_COUPON_CODE_SUCCESS',
  SET_WISHLIST_DATA: 'SET_WISHLIST_DATA',
  RESET_WISHLIST_DATA: 'RESET_WISHLIST_DATA',
  CLEAR_MAIN_CAT_FILTERS: 'CLEAR_MAIN_CAT_FILTERS',
  ADD_MAIN_CAT_FILTERS: 'ADD_MAIN_CAT_FILTERS',

  //Shipping
  SET_SHIPPING_ADDRESS: 'SET_SHIPPING_ADDRESS',
  SET_BILLING_ADDRESS: 'SET_BILLING_ADDRESS',
  SET_SAME_ADDRESS: 'SET_SAME_ADDRESS',

  SET_DIRTY_BILLING: 'SET_DIRTY_BILLING',
  SET_DIRTY_SHIPPING: 'SET_DIRTY_SHIPPING',
  GET_ALL_ADDRESS_LOGIN_USER: 'GET_ALL_ADDRESS_LOGIN_USER',
  CLEAR_ALL_ADDRESS_LOGIN_USER: 'CLEAR_ALL_ADDRESS_LOGIN_USER',

  IS_ADDRESS_SAVED: 'IS_ADDRESS_SAVED',

  SET_ADDRESS_LOADER: 'SET_ADDRESS_LOADER',
  SET_ACCOUNT_DATA: 'SET_ACCOUNT_DATA',
  RESET_ACCOUNT_STATE: 'RESET_ACCOUNT_STATE',

  SET_OUT_OF_STOCK_STATUS: 'SET_OUT_OF_STOCK_STATUS',

  //Set order detail
  SET_ORDER_DETAILS: 'SET_ORDER_DETAILS',

  SET_PRICES: 'SET_PRICES',
  SET_SHIPPING_METHOD_CART: 'SET_SHIPPING_METHOD_CART',
}
